name: mccf-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - numpy-financial
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - jupyterlab
  - ipykernel
  - openpyxl
  - xlrd
  - xlsxwriter
  - pyarrow
  - pyyaml
  - requests
  - httpx
  - tqdm
  - geopandas
  - shapely
  - geopy
  - fuzzywuzzy
  - python-Levenshtein
  - statsmodels
  - scikit-learn
  - sklearn-pandas
  - dash
  - dash-bootstrap-components
  - flask
  - flask-compress
  - pandera
  - pytest
  - pytest-cov
  - pre-commit
  - black
  - line_profiler
  - cython
  - tomli
  - typing_extensions
  - click
  - colorama
  - jinja2
  - markupsafe
  - packaging
  - tenacity
  - werkzeug
  - idna
  - charset-normalizer
  - urllib3
  - zipp
  - platformdirs
  - commonmark
  - rich
  - joblib
  - tables
  - contextily
  - keplergl
  # Additional packages for web application
  - folium=0.14.0
  - branca=0.6.0
  - pathlib2=2.3.7
  - pip
  - pip:
    - streamlit>=1.28.0